"""empty message

Revision ID: c4f01d6a11a7
Revises: 2268ee61f0e7
Create Date: 2023-07-06 16:15:27.758793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f01d6a11a7'
down_revision = '2268ee61f0e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_sweets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_sweets', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
